### ISSUE TITLE
Blog post: Less Painful Conference Calls

### ISSUE THREAD

**Issue by calumhalcrow** [RapidRiverSoftware/rapidriversoftware.github.io#103]
Topics:

Intro: calls are a necessary part of a remote-first working arrangement. Many of the problems with conf calls are the same problems faced by in-office meetings. Some good practices can help make them less painful:

- Consider Async: de-emphasise the need for meetings.

- Come prepared: prepare some notes on what you want to say.

- Publish an agenda and nominate a moderator: to ensure smooth handling.

- Use your webcam: communication happens via what you say, the tone you use, and your body language. Let others see you body language by using your webcam.

- Quiet room, no mute: easier to respond, no "sorry was on mute".

- Grok what others are saying: listen. Turn off distractions (Slack, phone on do-not-disturb, unnecessary browser tabs closed, email closed, etc.).

**Comment by monsteronfire** [comment]
This has been added to the [discourse thread](https://talk.rrsoft.co/t/blog-post-ideas/177), so I will close this.
