### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by calumhalcrow** [RapidRiverSoftware/rapidriversoftware.github.io#107]
Our site doesn't currently have a 404 page. It would be nice if it did, especially considering that links to old job posting might exist out in the wild.

I suggest a simple 404 page which highlights our current open positions (or even just a link to our Careers page).

**Comment by monsteronfire** [comment]
@calumhalcrow Sounds good. Will put it on my todo list 👍

**Comment by monsteronfire** [comment]
Associated PR: https://github.com/RapidRiverSoftware/rapidriversoftware.github.io/pull/109

**Comment by monsteronfire** [comment]
This has been merged.
