### ISSUE TITLE
Make contact form work

### ISSUE THREAD

**Issue by calumhalcrow** [RapidRiverSoftware/rapidriversoftware.github.io#24]
...by using https://formspree.io perhaps.

**Comment by calumhalcrow** [comment]
@snowflakekiller you totally don't have to do this, but if you'd like to by all means go for it 😄

**Comment by snowflakekiller** [comment]
@calumhalcrow done: https://github.com/RapidRiverSoftware/rapidriversoftware.github.io/pull/25
