### ISSUE TITLE
Instagram feed integration seems broken

### ISSUE THREAD

**Issue by calumhalcrow** [RapidRiverSoftware/rapidriversoftware.github.io#97]
See this screenshot:

<img width="749" alt="Screenshot 2019-11-21 at 2 41 49 PM" src="https://user-images.githubusercontent.com/277504/69313805-89bc2980-0c6d-11ea-9bd4-ad674cb30053.png">

**Comment by monsteronfire** [comment]
Working on it here: https://github.com/RapidRiverSoftware/rapidriversoftware.github.io/pull/98

**Comment by monsteronfire** [comment]
Resolved in https://github.com/RapidRiverSoftware/rapidriversoftware.github.io/pull/98

**Comment by calumhalcrow** [comment]
Thanks! 😄
